{
    "DataSutranMultas": [
        {"Empty": True, "PlacaValidate": "AHN426"},
        {"Empty": True, "PlacaValidate": "BAH829"},
        {"Empty": True, "PlacaValidate": "BJK093"},
        {"Empty": True, "PlacaValidate": "AUH614"},
        {"Empty": True, "PlacaValidate": "BUB203"},
        {"Empty": True, "PlacaValidate": "BCJ252"},
        {"Empty": True, "PlacaValidate": "BBS163"},
        {"Empty": True, "PlacaValidate": "D4B248"},
        {"Empty": True, "PlacaValidate": "AHK144"},
        {"Empty": True, "PlacaValidate": "AJF295"},
        {"Empty": True, "PlacaValidate": "D8R344"},
        {"Empty": True, "PlacaValidate": "AXM358"},
        {
            "PlacaValidate": "CFV251",
            "Documento": "2450619545",
            "Tipo": "Papeletas Transito",
            "FechaDoc": "2025-07-08",
            "CodigoInfrac": "M20",
            "Clasificacion": "Muy Grave",
            "LastUpdate": "2025-09-25",
        },
        {
            "PlacaValidate": "CFV251",
            "Documento": "2450547877",
            "Tipo": "Papeletas Transito",
            "FechaDoc": "2024-10-04",
            "CodigoInfrac": "M20",
            "Clasificacion": "Muy Grave",
            "LastUpdate": "2025-09-25",
        },
        {"Empty": True, "PlacaValidate": "CHO571"},
        {"Empty": True, "PlacaValidate": "AZK376"},
        {"Empty": True, "PlacaValidate": "ACU640"},
        {"Empty": True, "PlacaValidate": "ARD503"},
        {
            "PlacaValidate": "B9R276",
            "Documento": "2450603070",
            "Tipo": "Papeletas Transito",
            "FechaDoc": "2025-04-13",
            "CodigoInfrac": "M20",
            "Clasificacion": "Muy Grave",
            "LastUpdate": "2025-09-25",
        },
        {
            "PlacaValidate": "B9R276",
            "Documento": "2450304535",
            "Tipo": "Papeletas Transito",
            "FechaDoc": "2022-08-01",
            "CodigoInfrac": "M20",
            "Clasificacion": "Muy Grave",
            "LastUpdate": "2025-09-25",
        },
        {"Empty": True, "PlacaValidate": "BPS052"},
        {"Empty": True, "PlacaValidate": "LGB001"},
        {"Empty": True, "PlacaValidate": "BDM340"},
        {"Empty": True, "PlacaValidate": "ABE144"},
        {"Empty": True, "PlacaValidate": "BWM533"},
        {"Empty": True, "PlacaValidate": "B5L097"},
        {"Empty": True, "PlacaValidate": "CUF211"},
        {"Empty": True, "PlacaValidate": "C7Z073"},
    ]
}
